const a=document.body;
const root=a.querySelector('.id1');
const root2=a.querySelector('.id2');
const root3=a.querySelector('.id3');
const element=document.createElement('h1');
element.textContent='Hello, world!';
element.className='element';
element.id='first';
element.style.fontSize='80px';
root.append(element);
const element2=document.createElement('h2');
element2.textContent='Hello, everyone!';
element2.className='element';
element2.id='second';
element2.style.fontSize='60px';
root2.append(element2);
const element3=document.createElement('h3');
element3.textContent='Hello, all!';
element3.className='element';
element3.id='third';
element3.style.fontSize='40px';
root3.append(element3);
